version: 2

before:
  hooks:
    - go mod tidy

builds:
  - skip: true  # Skip internal GoReleaser build since you build manually

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - ./bin/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}  # Your prebuilt binaries
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [AwaisAmjad](https://github.com/awais/volk).
